# Site settings
title: Laelaps
email: info@specifkali.com
url: http://claytonerrington.com/clients/laelaps
description: "GPS Dog colalrs"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Laelaps

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/cjerrington
  - title: facebook
    url:

# Build settings
markdown: kramdown
permalink: pretty
